### ISSUE TITLE
Quickloading this savegame crashes engine

### ISSUE THREAD

**Issue by SpiritQuaddicted** [SpiritQuaddicted/reQuiem#35]
http://quaketastic.com/files/misc/requiem-crash-fmb6.7z is a savegame for https://www.quaddicted.com/reviews/fmb6.html

Trying to load it makes the engine crash/quit.

``` Quickloading...
Loading game from ./id1/quick.sav...
Detected fish-count bug in progs.dat; monster count has been adjusted
'ping' is not a field
'netaddress' is not a field
'playermodel' is not a field
'playerskin' is not a field
'cursor_trace_endpos' is not a field
'cursor_trace_start' is not a field
Error: First token isn't a brace
```

I am not sure if it was corrupted on writing

**Comment by SpiritQuaddicted** [comment]
Erm, on second look I am not sure what happened here. Apparently I did not save on fmb6 but this is an older quick save on e4m5. Sorry about that. Can't remember what I did there and how those fields (or non-fields) came to existence. Still, it crashes.

I am not sure if this is ok or not. At least it would be nice to just print the error to the console instead of quitting.

**Comment by SpiritQuaddicted** [comment]
Recent Quakespasm, Darkplaces and Tyrquake load it.
Fitzquake (Exe: 16:04:11 Jul  5 2008) behaves the same as reQuiem.
FTEQW prints the same "not a field" messages but loads it then.

**Comment by neogeographica** [comment]
It works if you delete the "DarkPlaces extended savegame" block from the end of the save file.

I haven't done any tests of a fix yet, but on code examination I see that COM_Parse in QuakeSpasm knows how to deal with C-style comment blocks in save files ("/\* ... */") while COM_Parse in reQuiem does not. Probably the next thing to do is to steal from QuakeSpasm and try changing this code:

``` c
// skip // comments
    if (c == '/' && data[1] == '/')
    {
        while (*data && *data != '\n')
            data++;
        goto skipwhite;
    }
```

to this:

``` c
// skip // comments
    if (c == '/' && data[1] == '/')
    {
        while (*data && *data != '\n')
            data++;
        goto skipwhite;
    }

// skip /*..*/ comments
    if (c == '/' && data[1] == '*')
    {
        data += 2;
        while (*data && !(*data == '*' && data[1] == '/'))
            data++;
        if (*data)
            data += 2;
        goto skipwhite;
    }
```

**Comment by neogeographica** [comment]
Yup that seems to do it. Going to test a bit more before doing a pull request.
