### ISSUE TITLE
Lighting bug?

### ISSUE THREAD

**Issue by Xylemon** [SpiritQuaddicted/reQuiem#42]
![lightingcomparison](https://cloud.githubusercontent.com/assets/7539500/3713509/831c1cf6-1570-11e4-9df5-419254d3b00d.png)
So I have this map I've been working on, and I've been testing it in reQuiem and other source ports, and this basically happens. It seems to be some odd error relating the the light maps be incorrectly rendered in Darkplaces and reQuiem. In WinQuake and Quakespasm it looks perfectly normal. What's going on?

**Comment by SpiritQuaddicted** [comment]
I have no idea but maybe this is related to http://forums.inside3d.com/viewtopic.php?f=3&t=5488

Can you compile yourself from the most recent version here and see if it is gone?

**Comment by neogeographica** [comment]
There's a current Windows build here (for a while) if you want to try it: https://dl.dropboxusercontent.com/u/11690738/temp/reQuiem.exe

**Comment by Xylemon** [comment]
@neogeographica Well I'm on Linux and I was wanting to use native binaries if possible rather than going through Wine. It's a nice option though if I can't get reQuiem to compile at all, so thanks for the binary.

EDIT: I ran this under Wine and the issue seems to be gone! I suppose this bug could be closed, I would just have to figure out how to compile the latest version.

@SpiritQuaddicted I tried compiling the project via Code::Blocks and I ended up getting this odd crash when running a debug compiled binary:

Received signal 11, exiting...

And when I attempt a release compile it claims it can't find these libraries:

/usr/bin/ld: skipping incompatible /usr/lib64/libXext.so when searching for -lXext
/usr/bin/ld: cannot find -lXext
/usr/bin/ld: skipping incompatible /usr/lib64/libXxf86dga.so when searching for -lXxf86dga
/usr/bin/ld: cannot find -lXxf86dga
/usr/bin/ld: skipping incompatible /usr/lib64/libXxf86vm.so when searching for -lXxf86vm
/usr/bin/ld: cannot find -lXxf86vm
/usr/bin/ld: skipping incompatible /usr/lib64/libasound.so when searching for -lasound
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status

Which is strange because I seem to have all these libraries installed.

**Comment by SpiritQuaddicted** [comment]
Hm, can you share the bsp?

I seem to have some trouble with master binaries too, trying to load any map in Quoth dose the signal 11, if I try with a debug binary it does not even launch the demo1 playback. I hate computers. :)

edit: That was the old makefile, everything is fine now.

**Comment by SpiritQuaddicted** [comment]
Ouch, I did not realise that the makefile was still broken by default. Please try a fresh pull. I hope it will work fine. I am on 64 bit and it is building a 32 bit binary for me. I did not touch the Codeblocks project, not sure what the status was there.

To build: make -f makefile.linux
To build a debug binary: make -f makefile.linux CC="gcc -g"

**Comment by Xylemon** [comment]
@SpiritQuaddicted 

Ok thanks for the updated makefile! It still didn't compile but I found out why, turns out I did not have the devel packages for the 32 bit versions of the libraries mentioned in my previous post. Now I can play Qreate on the latest version of ReQuiem with no lighting issues! As a result, I'm gonna close this issue since it just exists in an old build.

Also the map is here: http://euksy.oldtimes-software.com/files/Quake/qreate-0.8-release.zip
You can grab a copy and try it out!
