### ISSUE TITLE
Ammo counter only goes up to 154

### ISSUE THREAD

**Issue by Xylemon** [SpiritQuaddicted/reQuiem#45]
In Qreate, we have a weapon where its ammo is "666". When you run Qreate in reQuiem, the ammo counter only goes up to 154.

**Comment by neogeographica** [comment]
In the original Quake net protocol, a client's current ammo count is contained in one byte. So what you're seeing here is the value from lower 8 bits of 666, which gives you 154.

The "Fitzquake protocol" supports 16 bits of ammo count, but reQuiem doesn't use this by default. I'm not super familiar with all of reQuiem's protocol support, but on code inspection it looks like it can't act as a Fitzquake protocol server, only as a client. If that's the case then for singleplayer you'd be out of luck if you need that protocol.

**Comment by Xylemon** [comment]
Ah makes perfect sense, we even saw the same thing in DOSQuake. Gonna close this issue.
