### ISSUE TITLE
"con_notify" lines are not scaled with the hud

### ISSUE THREAD

**Issue by SpiritQuaddicted** [SpiritQuaddicted/reQuiem#6]
Add the notify lines to the hudscaled stuff. At the moment centerprints are glorious, but the normal notifications ("You picked up shells" etc) are not scaled like the rest. That is not ideal for video capture and high resolutions.

**Comment by neogeographica** [comment]
Either this was an optical illusion :-) or I'm misunderstanding the thing you're describing.

I checked the code for centerprints and conprints, and they seems to be using the same character drawing routine.

As a test I took screenshots at 1280x720 and then at 1920x1080, going into e1m1 and getting a centerprint and a pickup message. @ 1280x720 the centerprint and pickup message are both about 11 pixels tall; @ 1920x1080 they're both 16 pixels tall.

**Comment by neogeographica** [comment]
Ah ha, obviously you're talking about the effects of scr_hudscale.

So to have this effect it would need to have `SCR_SetHUDScale (true);` and `SCR_SetHUDScale (false);` bracketing the call that draws the message.

**Comment by SpiritQuaddicted** [comment]
Sorry, this was quoted from a mail. I meant the behaviour with "scr_hudscale X". I use "scr_hudscale 3". See the line in the top left compared to the centerprint:

scr_hudscale 3: http://i.imgur.com/imMYGAl.jpg

scr_hudscale 1: http://i.imgur.com/iUjceZM.jpg

**Comment by neogeographica** [comment]
You can check out the hudscale_notifies branch if you want to take it out for a spin.

I think there could be some problems with doing this; some comments on the commit https://github.com/SpiritQuaddicted/reQuiem/commit/af676ad515932c11116758d27cb8a8392a9d1890

**Comment by neogeographica** [comment]
Eh, after playing jam2 for a bit I got itchy to try the idea of using a separate scale for the notification messages. So if you get the tip of the hudscale_notifies branch now, it will have that. You can either set it through the menus or using scr_notifscale.

**Comment by SpiritQuaddicted** [comment]
Nice, thanks!

Do centerprints get wrapped or are they prone to be too wide too? I haven't noticed any issues with them when playing with scr_hudscale 3 for ever.

As for the amount of lines, con_notifylines is 4 by default which seems to work well with this (tried bigass1.dem).

I would suggest naming it scr_notifyscale instead of scr_notifscale, the term "notify" is used for con_notify\* too for example.

**Comment by neogeographica** [comment]
Centerprints seem OK to me. I don't know where all of them are... I just trundled around in the startmap and a few other places.

Cvar rename done... I'll roll the changes into master soon.
