### ISSUE TITLE
Sound Pitch Lower?

### ISSUE THREAD

**Issue by Xylemon** [SpiritQuaddicted/reQuiem#61]
It seems that the latest version of reQuiem plays sounds at a lower pitch, this is on Linux 64-bit with OSS4 build 2009

**Comment by SpiritQuaddicted** [comment]
Weird! Did you build it yourself? What version exactly? There were no sound code changes at all from what I know. Try playing with -sndspeed maybe?

**Comment by Xylemon** [comment]
Ok, I think I know what's going on. It's not any pitch altering, it's the way sounds are played in reQuiem. In other Quake source ports, the sounds have this compression playback to them (much like the original Quake), where in reQuiem they are very clean sounding. Some sounds such as the popup text sound, seemed lower pitch due to this. I'm going to close this issue since the sound is not lowered, but is there anyway to get that classic sound playback back?

**Comment by SpiritQuaddicted** [comment]
Probably sndspeed, s_khz or something.
